[server]
server_names = { "localhost", "2B5.local" }
host = "localhost"
port = 8080

root = "/var/www/html"
methods = { "GET", "POST", "DELETE" }

dirlist = false
uploads = false
cookies = false

cgi_path = "/bin/php"
cgi_ext = ".php"

client_max_body_size = "10M"

[server.error_pages]
404 = "not_found.html"
401 = "unauthorized.html"
402 = "uwu.html"

[server.location./]
methods = { "GET" }
root = "/var/www/html"
dirlist = true

[server.location./api]
methods = { "GET", "POST" }
uploads = true
root = "/var/www/api"
upload_path = "/etc/webserv/up"
cgi_path = "/bin/go"
cgi_ext = ".go"

[server.location./redir]
redirect = "https://kanel.ovh"
